name: Staging Env Content Sync

on:
  push:
    branches: [master]
    paths:
      - staging/**

jobs:
  Publish-Content:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Setup Environment Variables
        run: |
          echo "ENV=staging" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-gov-west-1" >> $GITHUB_ENV
          echo "BUCKET_NAME=cg-468c17da-3282-484a-ac00-8426e2a32594" >> $GITHUB_ENV
      - name: Sync from S3
        run: |
          mkdir $ENV
          cd $ENV
          aws s3 sync s3://$BUCKET_NAME .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync to S3
        run: |
          cd $ENV
          aws s3 sync . s3://$BUCKET_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configre S3 CORs
        run: |
          cd $ENV
          aws s3api put-bucket-cors --bucket $BUCKET_NAME --cors-configuration file://s3-cors-policy.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
